backend:
  name: git-gateway
  branch: main # Ветка, в которую сохранять изменения (обычно main или master)

media_folder: "images" # Куда админка будет сохранять загруженные картинки
public_folder: "images" # Как путь к картинкам будет выглядеть в коде

# Настройки для русского языка интерфейса (опционально)
locale: 'ru'

collections:
  - name: "blog"
    label: "Истории (Blog)"
    files:
      - name: "posts_ru"
        label: "Список статей (RU)"
        file: "blog.json" # Указываем, какой файл редактируем
        description: "Редактирование постов блога"
        fields:
          - name: "posts" # Это корневой список в JSON
            label: "Посты"
            widget: "list" # Тип поля: список
            fields:
              - {label: "ID (для ссылки)", name: "id", widget: "string", hint: "Например: post-magic-theory"}
              - {label: "Заголовок", name: "title", widget: "string"}
              - {label: "Главный пост (Featured)?", name: "featured", widget: "boolean", default: false}
              - {label: "Тег", name: "tag", widget: "string"}
              - {label: "Дата", name: "date", widget: "string"}
              - {label: "Обложка", name: "image", widget: "image"}
              - {label: "Краткое описание", name: "desc", widget: "text"}
              - {label: "Текст статьи", name: "content", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "quote", "bulleted-list"], editor_components: [], modes: ["rich_text", "raw"]}