backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

locale: 'ru'
display_url: "https://ericnorth.netlify.app"

collections:
  - name: "data"
    label: "Управление данными"
    files:
      - name: "blog"
        label: "Блог (Статьи)"
        file: "blog.json"
        fields:
          - name: "posts"
            label: "Список статей"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Заголовок", name: "title", widget: "string"}
              - {label: "Главный (Featured)", name: "featured", widget: "boolean", default: false, required: false}
              - {label: "Тег", name: "tag", widget: "string"}
              - {label: "Дата", name: "date", widget: "string"}
              - {label: "Обложка", name: "image", widget: "image", required: false}
              - {label: "Описание", name: "desc", widget: "text"}
              - {label: "Текст", name: "content", widget: "markdown"}
